language: python

python:
    - "3.6"

install:
    - pip install .
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    
script: 
    - paver
   
after_success:
    - codecov

